version: "3"
services:
  blog:
    build:
      context: .
      dockerfile: blog.Dockerfile
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # 配置域名
      - traefik.http.routers.blog.rule=Host(`wangshihao.top`)

      # 配置 TLS
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=le
      # - traefik.http.routers.blog.tls.certresolver=letsEncrypt
      
      # - "traefik.enable=true"
      # - "traefik.http.routers.blog.entrypoints=https"
      # - "traefik.http.routers.blog.service=api@internal"

      # - traefik.http.middlewares.my-redirect.redirectscheme.scheme=https
      # - traefik.http.routers.blog.middlewares=my-redirect

 

# 一定要与 traefik 在同一网络下
networks:
  default:
    external:
      name: traefik_default