version: "3"
services:
  blog:
    build:
      context: .
      dockerfile: blog.Dockerfile
    labels:
      # 配置域名
      - traefik.http.routers.blog.rule=Host(`wangshihao.top`)

      # 配置 TLS
      - traefik.http.routers.api.tls=true
      # - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.routers.api.tls.certresolver=letsEncrypt
      
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.service=api@internal"

# 一定要与 traefik 在同一网络下
networks:
  default:
    external:
      name: traefik_default